//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KatalogFilm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        public int IdFilm { get; set; }
        public int GenreId { get; set; }
        public string NamaFilm { get; set; }
        public System.DateTime TahunRilis { get; set; }
    
        public virtual Genre Genre { get; set; }
    }
}
